export const STORES = [
  { name: "Apotek 1", url: "https://www.apotek1.no", category: "helse" },
  { name: "Anton Sport", url: "https://www.antonsport.no", category: "sport" },
  { name: "Bjørklund", url: "https://www.bjorklund.no", category: "gull" },
  { name: "CEWE Japan Photo", url: "https://www.japanphoto.no", category: "foto" },
  { name: "Clas Ohlson", url: "https://www.clasohlson.com/no", category: "hjem" },
  { name: "Feel", url: "https://www.feel.no", category: "helse" },
  { name: "Funky Frozen Yogurt", url: "https://www.ffy.no", category: "mat" },
  { name: "GANT", url: "https://www.gant.no", category: "mote" },
  { name: "Glitter", url: "https://www.glitter.no", category: "tilbehør" },
  { name: "Hællæ", url: "https://www.haellae.no", category: "mat" },
  { name: "Jernia", url: "https://www.jernia.no", category: "hjem" },
  { name: "Kid Interiør", url: "https://www.kid.no", category: "interiør" },
  { name: "Kitch'n", url: "https://www.kitchn.no", category: "kjøkken" },
  { name: "Lekia", url: "https://www.lekia.no", category: "leker" },
  { name: "Life", url: "https://www.life.no", category: "helse" },
  { name: "Mester Grønn", url: "https://www.mestergronn.no", category: "blomster" },
  { name: "Nille", url: "https://www.nille.no", category: "lavpris" },
  { name: "Nikita Hair", url: "https://www.nikita.no", category: "frisør" },
  { name: "Normal", url: "https://www.normal.no", category: "lavpris" },
  { name: "Norli", url: "https://www.norli.no", category: "bøker" },
  { name: "Næss", url: "https://www.naess.as", category: "sko" },
  { name: "Outland", url: "https://www.outland.no", category: "underholdning" },
  { name: "Presangen", url: "https://www.presangen.no", category: "gaver" },
  { name: "Rituals", url: "https://www.rituals.com/nb-no/home", category: "duft" },
  { name: "Rino Hansen", url: "https://rinohansen.no", category: "sko" },
  { name: "SmoothieXchange", url: "https://www.smoothiexchange.no", category: "mat" },
  { name: "Synsam", url: "https://www.synsam.no", category: "optikk" },
  { name: "Telenor", url: "https://www.telenor.no", category: "tele" },
  { name: "Trio Barn", url: "https://triobarn.no", category: "barn" },
  { name: "VIC", url: "https://www.vic.no", category: "mote" },
  { name: "Vinmonopolet", url: "https://www.vinmonopolet.no", category: "drikke" },
  { name: "Vita", url: "https://www.vita.no", category: "helse" },
  { name: "Matværste", url: "https://matvaerste.no", category: "mat" },
  { name: "Obs Fredrikstad", url: "https://www.obs.no", category: "dagligvare" },
  { name: "Power", url: "https://www.power.no", category: "elektronikk" },
  { name: "EVO Fitness", url: "https://evofitness.no", category: "trening" },
  { name: "Therese M", url: "https://www.theresem.no", category: "mote" },
]