export const STORES = [
  { name: "Apotek 1", url: "https://www.apotek1.no", category: "helse", instagram: "apotek1no", facebook: "Apotek1" },
  { name: "Anton Sport", url: "https://www.antonsport.no", category: "sport", instagram: "anton_sport", facebook: "antonsport" },
  { name: "Bjørklund", url: "https://www.bjorklund.no", category: "gull", instagram: "bjorklundofficial", facebook: "bjorklundlykkesmed" },
  { name: "CEWE Japan Photo", url: "https://www.japanphoto.no", category: "foto", instagram: "cewejapanphoto", facebook: "CEWEJapanPhoto" },
  { name: "Clas Ohlson", url: "https://www.clasohlson.com/no", category: "hjem", instagram: "clasohlsonnorge", facebook: "ClasOhlsonNorge" },
  { name: "Feel", url: "https://www.feel.no", category: "helse", instagram: "feel_norge", facebook: "feelnorge" },
  { name: "Funky Frozen Yogurt", url: "https://www.ffy.no", category: "mat", instagram: "funkyfrozenyogurt", facebook: "FunkyFrozenYogurt" },
  { name: "GANT", url: "https://www.gant.no", category: "mote", instagram: "gant.norge", facebook: "GANTNorge" },
  { name: "Glitter", url: "https://www.glitter.no", category: "tilbehør", instagram: "glitter_norge", facebook: "GlitterNorge" },
  { name: "Hællæ", url: "https://www.haellae.no", category: "mat" },
  { name: "Jernia", url: "https://www.jernia.no", category: "hjem", instagram: "jernia", facebook: "jernia" },
  { name: "Kid Interiør", url: "https://www.kid.no", category: "interiør", instagram: "kidinterior", facebook: "kid" },
  { name: "Kitch'n", url: "https://www.kitchn.no", category: "kjøkken", instagram: "kitchnnorge", facebook: "kitchn.no" },
  { name: "Lekia", url: "https://www.lekia.no", category: "leker", instagram: "lekia_norge", facebook: "lekianorge" },
  { name: "Life", url: "https://www.life.no", category: "helse", instagram: "lifenorge", facebook: "LifeHelse" },
  { name: "Mester Grønn", url: "https://www.mestergronn.no", category: "blomster", instagram: "mestergronn", facebook: "mestergronn" },
  { name: "Nille", url: "https://www.nille.no", category: "lavpris", instagram: "nillenorge", facebook: "nillenorge" },
  { name: "Nikita Hair", url: "https://www.nikita.no", category: "frisør", instagram: "nikitahair", facebook: "NikitaHair" },
  { name: "Normal", url: "https://www.normal.no", category: "lavpris", instagram: "normal_norge", facebook: "NORMALNorge" },
  { name: "Norli", url: "https://www.norli.no", category: "bøker", instagram: "norli_bokhandel", facebook: "NorliBokhandel" },
  { name: "Næss", url: "https://www.naess.as", category: "sko", instagram: "naessfredrikstad", facebook: "naessfredrikstad" },
  { name: "Outland", url: "https://www.outland.no", category: "underholdning", instagram: "outlandfredrikstad", facebook: "outlandfredrikstad" },
  { name: "Presangen", url: "https://www.presangen.no", category: "gaver", instagram: "presangen_fredrikstad", facebook: "presangen" },
  { name: "Rituals", url: "https://www.rituals.com/nb-no/home", category: "duft", instagram: "ritualscosmetics", facebook: "RitualsCosmeticsNO" },
  { name: "Rino Hansen", url: "https://rinohansen.no", category: "sko", instagram: "rinohansen", facebook: "rinohansen.torvbyen" },
  { name: "SmoothieXchange", url: "https://www.smoothiexchange.no", category: "mat", instagram: "smoothiexchange", facebook: "SmoothieXchange" },
  { name: "Synsam", url: "https://www.synsam.no", category: "optikk", instagram: "synsamnorge", facebook: "SynsamNorge" },
  { name: "Telenor", url: "https://www.telenor.no", category: "tele", instagram: "telenornorge", facebook: "telenornorge" },
  { name: "Trio Barn", url: "https://triobarn.no", category: "barn", instagram: "triobarnfredrikstad", facebook: "nameittorvbyen" },
  { name: "VIC", url: "https://www.vic.no", category: "mote", instagram: "vic.norge", facebook: "VIC" },
  { name: "Vinmonopolet", url: "https://www.vinmonopolet.no", category: "drikke", instagram: "asvinmonopolet", facebook: "Vinmonopolet" },
  { name: "Vita", url: "https://www.vita.no", category: "helse", instagram: "vita_no", facebook: "vita" },
  { name: "Matværste", url: "https://matvaerste.no", category: "mat", instagram: "matvaerste", facebook: "matvaerste" },
  { name: "Obs Fredrikstad", url: "https://www.obs.no", category: "dagligvare", instagram: "obs.no", facebook: "Obs-Fredrikstad" },
  { name: "Power", url: "https://www.power.no", category: "elektronikk", instagram: "powernorge", facebook: "powernorge" },
  { name: "EVO Fitness", url: "https://evofitness.no", category: "trening", instagram: "evonorge", facebook: "evotreningssenter" },
  { name: "Therese M", url: "https://www.theresem.no", category: "mote", instagram: "theresem.no", facebook: "Therese-M" },
]
